// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1) {
  return window['go']['main']['App']['CheckoutBranch'](arg1);
}

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function DiscardChanges(arg1) {
  return window['go']['main']['App']['DiscardChanges'](arg1);
}

export function Fetch() {
  return window['go']['main']['App']['Fetch']();
}

export function GetBranches() {
  return window['go']['main']['App']['GetBranches']();
}

export function GetCommitGraph(arg1) {
  return window['go']['main']['App']['GetCommitGraph'](arg1);
}

export function GetCurrentBranch() {
  return window['go']['main']['App']['GetCurrentBranch']();
}

export function GetDiff(arg1, arg2) {
  return window['go']['main']['App']['GetDiff'](arg1, arg2);
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetHunks(arg1, arg2) {
  return window['go']['main']['App']['GetHunks'](arg1, arg2);
}

export function GetLog(arg1) {
  return window['go']['main']['App']['GetLog'](arg1);
}

export function GetRepositoryPath() {
  return window['go']['main']['App']['GetRepositoryPath']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenRepository(arg1) {
  return window['go']['main']['App']['OpenRepository'](arg1);
}

export function OpenTerminal() {
  return window['go']['main']['App']['OpenTerminal']();
}

export function Pull() {
  return window['go']['main']['App']['Pull']();
}

export function Push() {
  return window['go']['main']['App']['Push']();
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['main']['App']['StageFile'](arg1);
}

export function StageHunks(arg1, arg2, arg3) {
  return window['go']['main']['App']['StageHunks'](arg1, arg2, arg3);
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['main']['App']['UnstageFile'](arg1);
}

export function UnstageHunks(arg1, arg2) {
  return window['go']['main']['App']['UnstageHunks'](arg1, arg2);
}
