// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';

export function CheckoutBranch(arg1:string):Promise<string>;

export function Commit(arg1:string):Promise<string>;

export function DiscardChanges(arg1:string):Promise<string>;

export function Fetch():Promise<string|string>;

export function GetBranches():Promise<Array<git.Branch>|string>;

export function GetCommitGraph(arg1:number):Promise<Array<git.GraphNode>|string>;

export function GetCurrentBranch():Promise<string|string>;

export function GetDiff(arg1:string,arg2:boolean):Promise<string|string>;

export function GetFileContent(arg1:string):Promise<string|string>;

export function GetHunks(arg1:string,arg2:boolean):Promise<Array<git.DiffHunk>|string>;

export function GetLog(arg1:number):Promise<Array<git.Commit>|string>;

export function GetRepositoryPath():Promise<string>;

export function GetStatus():Promise<Array<git.FileStatus>|string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenRepository(arg1:string):Promise<boolean|string>;

export function OpenTerminal():Promise<string>;

export function Pull():Promise<string|string>;

export function Push():Promise<string|string>;

export function StageAll():Promise<string>;

export function StageFile(arg1:string):Promise<string>;

export function StageHunks(arg1:string,arg2:Array<number>,arg3:boolean):Promise<string>;

export function UnstageAll():Promise<string>;

export function UnstageFile(arg1:string):Promise<string>;

export function UnstageHunks(arg1:string,arg2:Array<number>):Promise<string>;
